name: Production Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
     contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check release.md
        run: |
          if [[ ! -f latest_changelog.md ]]; then
              exit 1
          fi

      - name: Determine Release Type from Changelog
        run: |
          FIRST_LINE=$(head -n 1 latest_changelog.md)
          [[ "$FIRST_LINE" == *"[PRE-RELEASE]"* ]] && echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          sed -i '2d' latest_changelog.md

      - name: Create Module ZIP
        run: |
          VERSION_NAME="${GITHUB_REF_NAME}"
          ZIP_NAME="bootanimation-module-${VERSION_NAME}.zip"
          zip -r9 "$ZIP_NAME" . -x ".git/*" -x ".github/*" -x ".gitignore" -x latest_changelog.md
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }} | 🌌 Bootanimation Module
          files: ${{ env.ZIP_NAME }}
          prerelease: ${{ env.IS_PRERELEASE }}
          body_path: latest_changelog.md
