name: ShellCheck

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2
